### ISSUE TITLE
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>

### ISSUE THREAD

**Issue by nikaslg** [peachananr/onepage-scroll#347]
Provides default event error in the console. I would say not production usable.

**Comment by x4r7** [comment]
+

**Comment by slejnej** [comment]
Hi,
had same problem. After investigation and reported solution from Firefox developers this is due to "the way the event is attached". So in order to fix this add this to your .js file at the end:

`
jQuery.event.special.mousewheel = {
    setup: function( _, ns, handle ){
        console.log(ns);
        if ( ns.includes("noPreventDefault") ) {
            this.addEventListener("mousewheel", handle, { passive: true });
        } else {
            this.addEventListener("mousewheel", handle, { passive: false });
        }
    }
};
`

so for events when you do want to use passive mode you just call that event 'mousewheel.noPreventDefault' instead just 'mousewheel'

Tested this with big js file with a lot of code and listeners and it works. Same error can happen if you use 'touchstart' and 'touchend'. the just create separate entry of attached code and replace all 'mousewheel' with these.

hope it helped and saved someone some time ;)
